### ISSUE TITLE
Can I adapt the main function of this CLI to link it to a tool I am making ?

### ISSUE THREAD

**Issue by TeoDev1611** [postui/publish#2]
Hi, I'm working on merging some cool CLIs from the Deno ecosystem into a tool like [npm](https://npmjs.org) and I want to merge this tool with the [dpm](https://github.com/dpmland/dpm) project and make this part of the CLI with a command: `dpm publish`  with credits to this project and its author.

Thank you for this amazing work.

**Comment by ije** [comment]
yes！free to merge！

**Comment by TeoDev1611** [comment]
Thanks 🦕
